src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>fr_ID__c</fullName>
        <externalId>true</externalId>
        <label>Funraise External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>fr_ID__c</fullName>
        <description>Funraise ID for campaigns in platform</description>
        <externalId>true</externalId>
        <label>Funraise ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Funraise Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Donations</relationshipLabel>
        <relationshipName>Donations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>fr_Donor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Funraise Donor</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Funraise Donations</relationshipLabel>
        <relationshipName>fr_Donations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>fr_ID__c</fullName>
        <externalId>true</externalId>
        <label>Funraise ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/Pledge__c.object
<CustomObject>
    <fields>
        <fullName>Campaign_Page__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign Page</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Funraise Pledges</relationshipLabel>
        <relationshipName>Funraise_Pledges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>The date on which this pledge should be considered inactive and donations will stop automatically counting towards fulfilling it</description>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Percent_Complete__c</fullName>
        <formula>Received_Amount__c/Pledge_Amount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Percent Complete</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Pledge_Amount__c</fullName>
        <description>The total amount for this pledge</description>
        <label>Pledge Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Pledge_Donation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Note: This field will only be filled out for pledges that are created directly from Funraise.  These pledges don&apos;t get fulfilled by multiple donations, only a single donation represented by this lookup field</description>
        <inlineHelpText>Note: This field will only be filled out for pledges that are created directly from Funraise.  These pledges don&apos;t get fulfilled by multiple donations, only a single donation represented by this lookup field</inlineHelpText>
        <label>Pledge Donation</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Funraise Pledges</relationshipLabel>
        <relationshipName>Funraise_Pledges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pledge_Donation_uq__c</fullName>
        <description>Only one pledge may reference an given opportunity as it&apos;s sole pledge donation.  This field enforces that since we can&apos;t make the lookup field unique</description>
        <externalId>true</externalId>
        <label>Pledge Donation (unique)</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Pledge_Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The subscription that created this pledge</description>
        <inlineHelpText>The subscription that created this pledge</inlineHelpText>
        <label>Pledge Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Funraise Pledges</relationshipLabel>
        <relationshipName>Funraise_Pledges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pledge_Subscription_uq__c</fullName>
        <externalId>true</externalId>
        <label>Pledge Subscription (unique)</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Received_Amount__c</fullName>
        <description>Summed opportunity amounts related to this pledge.  Calculation of this value is handled by a trigger whenever opportunities related to this pledge are added or updated</description>
        <inlineHelpText>This value is calculated automatically by a trigger whenever opportunities related to this pledge are added or updated</inlineHelpText>
        <label>Received Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>The date at which this pledge should be considered active and have donations automatically count towards fulfilling the pledge</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Supporter_PA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Person Account(if enabled) that represents the Funraise supporter that owns this pledge</description>
        <label>Funraise PA Supporter</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Funraise Pledges</relationshipLabel>
        <relationshipName>Funraise_Pledges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Supporter__c</fullName>
        <description>The contact that represents the Funraise supporter that owns this pledge</description>
        <label>Funraise Supporter</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Funraise Pledges</relationshipLabel>
        <relationshipName>Funraise_Pledges</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>fr_Id__c</fullName>
        <externalId>true</externalId>
        <label>Funraise ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Funraise Pledge</label>
    <nameField>
        <label>Funraise Pledge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funraise Pledges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Subscription__c.object
<CustomObject>
    <fields>
        <fullName>Supporter__c</fullName>
        <label>Supporter</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Funraise Subscriptions</relationshipLabel>
        <relationshipName>Funraise_Subscriptions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>fr_ID__c</fullName>
        <externalId>true</externalId>
        <label>Funraise ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Funraise Subscription</label>
    <nameField>
        <label>Funraise Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funraise Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Sync_Attempt__c.object
<CustomObject>
    <label>Funraise Sync Attempt</label>
    <nameField>
        <displayFormat>S-{0000000}</displayFormat>
        <label>Funraise Sync Attempt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funraise Sync Attempts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/frPledge.cls
/*
*
*  Copyright (c) 2020, Funraise Inc
*  All rights reserved.
*
*  Redistribution and use in source and binary forms, with or without
*  modification, are permitted provided that the following conditions are met:
*  1. Redistributions of source code must retain the above copyright
*     notice, this list of conditions and the following disclaimer.
*  2. Redistributions in binary form must reproduce the above copyright
*     notice, this list of conditions and the following disclaimer in the
*     documentation and/or other materials provided with the distribution.
*  3. All advertising materials mentioning features or use of this software
*     must display the following acknowledgement:
*     This product includes software developed by the <organization>.
*  4. Neither the name of the <organization> nor the
*     names of its contributors may be used to endorse or promote products
*     derived from this software without specific prior written permission.
*
*  THIS SOFTWARE IS PROVIDED BY FUNRAISE INC ''AS IS'' AND ANY
*  EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
*  WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
*  DISCLAIMED. IN NO EVENT SHALL FUNRAISE INC BE LIABLE FOR ANY
*  DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
*  (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
*  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
*  ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
*  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
*  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*
*
*
* PURPOSE:  A class for representing a Funraise pledge.  Used for creating & matching to pledges
*
*
*
* CREATED: 2020 Funraise Inc - https://funraise.io
* AUTHOR: Alex Molina
*/
public class frPledge extends frModel implements frSyncable {

    public frPledge(Sync_Attempt__c syncRecord) {
        super(syncRecord);
    }

    public Boolean sync() {
        Boolean result = false;
        Map<String, Object> request = getRequestBody();
        if (Boolean.valueOf(request.get('deleted'))) {
            result = deletePledge(request);
        } else {
            result = create(request);
        }
        return result;
    }

    protected override Set<SObjectField> getFields() {
        return new Set<Schema.SObjectField> {
                Pledge__c.Name,
                Pledge__c.End_Date__c,
                Pledge__c.Start_Date__c,
                Pledge__c.Pledge_Amount__c,
                Pledge__c.Received_Amount__c,
                Pledge__c.fr_Id__c,
                Pledge__c.Campaign_Page__c,
                Pledge__c.Pledge_Subscription__c
        };
    }

    protected override Set<SObjectType> getObjects() {
        return new Set<Schema.SObjectType> {
                Pledge__c.SObjectType
        };
    }

    protected override frUtil.Entity getFrType() {
        return frUtil.Entity.PLEDGE;
    }

    protected override String getFunraiseId() {
        return String.valueOf(getRequestBody().get('commitmentId'));
    }

    private Boolean create(Map<String, Object> request) {
        Boolean result = false;
        String commitmentId = getFunraiseId();
        String pledgeAmount = String.valueOf(request.get('amount'));
        String pledgeTotalAmount = String.valueOf(request.get('totalDonationAmount'));

        Pledge__c pledge = new Pledge__c(
                Name = frUtil.truncateToFieldLength(Pledge__c.Name.getDescribe(), 'Commitment - ' + String.valueOf(request.get('name'))),
                Pledge_Amount__c = String.isNotBlank(pledgeAmount) ? Decimal.valueOf(pledgeAmount) : null,
                Received_Amount__c = String.isNotBlank(pledgeTotalAmount) ? Decimal.valueOf(pledgeTotalAmount) : 0,
                fr_Id__c = commitmentId,
                End_Date__c = convertFromLocalDate((List<Object>) request.get('collectDate'))
        );

        SObject supporter = null;
        String funraiseSupporterId = String.valueOf(request.get('supporterId'));
        if(String.isNotBlank(funraiseSupporterId)) {
            List<SObject> supporters;
            if (frUtil.hasNPCobjects()) {
                supporters = [SELECT Id FROM Account WHERE fr_Id__c = :funraiseSupporterId];
            } else {
                supporters = [SELECT Id, AccountId FROM Contact WHERE fr_Id__c = :funraiseSupporterId];
            }
            if(supporters.isEmpty() && createLogRecord) {
                frUtil.logRelationshipError(getFrType(), commitmentId, frUtil.Entity.SUPPORTER, funraiseSupporterId);
            } else if (!supporters.isEmpty()) {
                supporter = supporters.get(0);
            }
        }

        if(frUtil.hasNPCobjects()) {
            pledge.put('Supporter_PA__c', supporter?.Id);
        } else {
            pledge.Supporter__c = supporter?.Id;
        }

        //connect campaign
        String campaignId = String.valueOf(request.get('goalId'));
        if (String.isNotBlank(campaignId)) {
            List<Campaign> campaigns = [SELECT Id FROM Campaign WHERE fr_ID__c = :campaignId];
            if (campaigns.size() > 0) {
                pledge.put('Campaign_Page__c', campaigns[0].Id);
            } else {
                frUtil.logRelationshipError(getFrType(), commitmentId, frUtil.Entity.CAMPAIGN, campaignId);
            }
        }

        try {
            Database.upsert(pledge, Pledge__c.fr_Id__c, true);
            result = true;
        } catch (DMLException ex) {
            if(createLogRecord) {
                frUtil.logException(getFrType(), commitmentId, ex);
            }
        }

        return result;
    }

    private Boolean deletePledge(Map<String, Object> request) {
        Boolean result = false;
        String commitmentId = getFunraiseId();
        try {
            List<Pledge__c> pledges = [SELECT Id, fr_ID__c FROM Pledge__c WHERE fr_ID__c = :commitmentId];
            if(pledges.size() == 0) {
                return true;
            }
            Pledge__c pledgeToDelete = pledges.get(0);
            delete pledgeToDelete;
            result = true;
        } catch (DMLException e) {
            if(createLogRecord) {
                frUtil.logException(getFrType(), commitmentId, e);
            }
        }
        return result;
    }

    public static Pledge__c findActive(Id contactId, Date closeDate) {
        List<Pledge__c> possiblePledges = [SELECT Id FROM Pledge__c 
                                         WHERE Supporter__c = :contactId 
                                         AND (Start_Date__c = null OR Start_Date__c <= :closeDate)
                                         AND (End_Date__c = null OR End_Date__c >= :closeDate)
                                         AND Percent_Complete__c < 100
                                         AND Pledge_Donation__c = null
                                         ORDER BY CreatedDate ASC LIMIT 1
                                        ];
        return possiblePledges.size() > 0 ? possiblePledges.get(0) : null;
    }

    public static Pledge__c findActiveAcc(Id accountId, Date closeDate) {
        List<Pledge__c> possiblePledges = [SELECT Id FROM Pledge__c 
                                         WHERE Supporter_PA__c = :accountId 
                                         AND (Start_Date__c = null OR Start_Date__c <= :closeDate)
                                         AND (End_Date__c = null OR End_Date__c >= :closeDate)
                                         AND Percent_Complete__c < 100
                                         AND Pledge_Donation__c = null
                                         ORDER BY CreatedDate ASC LIMIT 1
                                        ];
        return possiblePledges.size() > 0 ? possiblePledges.get(0) : null;
    }
    
    public static Pledge__c create(Opportunity opp) {
        Pledge__c pledge = new Pledge__c(
            Name = frUtil.truncateToFieldLength(Pledge__c.Name.getDescribe(), opp.Name + ' Pledge'),
            Supporter__c = opp.fr_Donor__c,
            Pledge_Amount__c = opp.Amount,
            Pledge_Donation__c = opp.Id,
            Pledge_Donation_uq__c = opp.Id
        );

        try {
            Database.upsert(pledge, Pledge__c.Fields.Pledge_Donation_uq__c, true);
            opp.Funraise_Pledge__c = pledge.Id;
            update opp;
        } catch (Exception ex) {
            frUtil.logException(frUtil.Entity.PLEDGE, opp.fr_Id__c, ex);
        }
        
        return pledge;
    }
    
    public static Pledge__c create(Subscription__c subscription, Decimal pledgeAmount) {
        Pledge__c pledge = new Pledge__c(
            Name = frUtil.truncateToFieldLength(Pledge__c.Name.getDescribe(), 'Subscription Pledge - ' + subscription.Name),
            Supporter__c = subscription.Supporter__c,
            Pledge_Amount__c = pledgeAmount,
            Pledge_Subscription__c = subscription.Id,
            Pledge_Subscription_uq__c = subscription.Id
        );
        try {
            Database.upsert(pledge, Pledge__c.Pledge_Subscription_uq__c , true);
        } catch (Exception ex) {
            frUtil.logException(frUtil.Entity.PLEDGE, subscription.fr_Id__c, ex);
        }
        
        return pledge;
    }

    public static Pledge__c create(SObject gc, Decimal pledgeAmount) {
        Id relatedId = (Id) gc.get('Id');
        Id donorId = (Id) gc.get('DonorId');
        SObject acc = Database.query('SELECT PersonContactId FROM Account WHERE Id = :donorId');
        Pledge__c pledge = new Pledge__c(
            Name = frUtil.truncateToFieldLength(Pledge__c.Name.getDescribe(), 'Subscription Pledge - ' + (String) gc.get('Name')),
            Supporter__c =(id) acc.get('PersonContactId'),
            Supporter_PA__c = (id) gc.get('DonorId'),
            Pledge_Amount__c = pledgeAmount,
            Pledge_Subscription__c = relatedId,
            Pledge_Subscription_uq__c = relatedId
        );
        try {
            Database.upsert(pledge, Pledge__c.Pledge_Subscription_uq__c , true);
        } catch (Exception ex) {
            frUtil.logException(frUtil.Entity.PLEDGE, (String) gc.get('fr_Id__c'), ex);
        }
        
        return pledge;
    }

    public static Pledge__c create(SObject gt) {
        Id relatedId = (Id) gt.get('Id');
        Id donorId = (Id) gt.get('DonorId');
        SObject acc = Database.query('SELECT PersonContactId FROM Account WHERE Id = :donorId');
        Map<String,Object> gtMap = gt.getPopulatedFieldsAsMap();
        Pledge__c pledge = new Pledge__c(
            Name = frUtil.truncateToFieldLength(Pledge__c.Name.getDescribe(), gtMap.get('Name') == null ? '' : gtMap.get('Name')+' Pledge'),
            Supporter__c =(id) acc.get('PersonContactId'),
            Supporter_PA__c = (id) gt.get('DonorId'),
            Pledge_Amount__c = (Decimal) (gtMap.get('OriginalAmount') ?? 0.0),
            Pledge_Donation_uq__c = relatedId
        );
        pledge.put('Pledge_Gift_Transaction__c', relatedId);
        try {
            Database.upsert(pledge);
            gt.put('Funraise_GT_Pledge__c', pledge.Id);
            update gt;
        } catch (Exception ex) {
            frUtil.logException(frUtil.Entity.PLEDGE, (String) gt.get('fr_Id__c'), ex);
        }
        
        return pledge;
    }
}