src/objects/Error__c.object
<CustomObject>
    <fields>
        <fullName>Error__c</fullName>
        <label>Error</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Funraise Error</label>
    <nameField>
        <label>Funraise Error Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funraise Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sync_Attempt__c.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DONATION</fullName>
                </value>
                <value>
                    <fullName>SUPPORTER</fullName>
                </value>
                <value>
                    <fullName>EVENT</fullName>
                </value>
                <value>
                    <fullName>REGISTRATION</fullName>
                </value>
                <value>
                    <fullName>SUBSCRIPTION</fullName>
                </value>
                <value>
                    <fullName>CAMPAIGN</fullName>
                </value>
                <value>
                    <fullName>EMAIL</fullName>
                </value>
                <value>
                    <fullName>TASK</fullName>
                </value>
                <value>
                    <fullName>PLEDGE</fullName>
                </value>
                <value>
                    <fullName>QUESTION</fullName>
                </value>
                <value>
                    <fullName>ANSWER</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Funraise Sync Attempt</label>
    <nameField>
        <displayFormat>S-{0000000}</displayFormat>
        <label>Funraise Sync Attempt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funraise Sync Attempts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/frTestUtil.cls
public class frTestUtil {
    public static void assertNoErrors() {
        List<Error__c> errors = [SELECT Error__c, Funraise_Object__c FROM Error__c];
        String errorsStr = '';
        for(Error__c error : errors) {
            errorsStr +=  '==Object ' + error.Funraise_Object__c + '==\n' +
                'Error: ' +error.Error__c + '\n';
        }
        System.assertEquals(0, errors.size(), 'There were unexpected errors. Errors:' + errorsStr);
        
        List<Sync_Attempt__c> savedSyncAttempts = [SELECT Id, Type__c FROM Sync_Attempt__c];
        String syncErrorStr = '';
        for(Sync_Attempt__c attempt : savedSyncAttempts) {
            syncErrorStr += '==Type: ' + attempt.Type__c;
        }
        System.assertEquals(0, savedSyncAttempts.size(), 'There were unexpected saved sync attempts:' + syncErrorStr);
    }
    
        
    public static void createTestPost(Map<String, Object> request) {
        createTestPost(Blob.valueOf(Json.serialize(request)));
    }
    
    public static void createTestPost(Blob requestBody) {
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = 'https://XXXX.salesforce.com/services/apexrest/funraise/v1';
        req.httpMethod = 'POST';
        req.requestBody = requestBody;
        RestContext.request = req;
        RestContext.response = res;
    }
}